services:
  localstack:
    image: gresau/localstack-persist:latest
    container_name: cdw_localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
      DEFAULT_REGION: us-east-1
      PERSIST_S3: 1
    volumes:
      - localstack_data:/persisted-data
    networks:
      - airflow
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  localstack-init:
    image: amazon/aws-cli:latest
    container_name: cdw_localstack_init
    depends_on:
      localstack:
        condition: service_healthy
    networks:
      - airflow
    env_file:
      - .localstack.env
    environment:
      AWS_DEFAULT_REGION: us-east-1
    entrypoint: >
      /bin/sh -c "
      aws --endpoint-url=http://localstack:4566 s3 mb s3://civic-data-warehouse-lz 2>/dev/null || true;
      echo 'Bucket civic-data-warehouse-lz created';
      "

  cdw-postgres:
    image: postgres:15
    container_name: cdw_postgres
    ports:
      - "5433:5432"
    env_file:
      - .postgres_cdw.env
    volumes:
      - cdw_postgres_data:/var/lib/postgresql/data
    networks:
      - airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  scheduler:
    env_file:
      - .airflow.env
  api-server:
    env_file:
      - .airflow.env
  dag-processor:
    env_file:
      - .airflow.env
  triggerer:
    env_file:
      - .airflow.env
      
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    networks:
      - airflow
    ports:
      - "127.0.0.1:8081:80"
    env_file:
      - .pgadmin.env

volumes:
  localstack_data:
  cdw_postgres_data:

networks:
  airflow: